name: CI/CD
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build, Test and Quality Gates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=salvatorebottiglieri_consigliaviaggi -Dsonar.qualitygate.wait=true
  
  deploy:
    name: Deploy on Raspberry
    runs-on: self-hosted
    needs: build
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Update codebase
        run: git pull
        
      #- name: Kill server # kill process if already running
        #run: kill $(ps -ef | grep -v grep | grep java | awk '{print $2}')
      
      - name: Packaging of code 
        run: mvn clean package spring-boot:repackage
        
      - name: Code execution
        run: nohup java -jar ./target/consigliaviaggi-1.1.jar &
