name: Deploy to Raspberry Pi

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["BuildAndTest","SonarCloud"]
    types:
      - completed
      
jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Update codebase
        run: git pull
        
      - name: Kill server # kill process if already running
        run: kill $(ps -ef | grep -v grep | grep java | awk '{print $2}')
      
      - name: Packaging of code 
        run: mvn clean package spring-boot:repackage
        
      - name: Code execution
        run: nohup java -jar ./target/consigliaviaggi-1.1.jar &
